# Generated by Django 2.2.2 on 2019-06-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190624_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
