# Generated by Django 2.2.2 on 2019-06-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190625_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
