# Generated by Django 2.2.2 on 2019-08-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190625_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='text',
            new_name='Wish_Text',
        ),
    ]
